# El algoritmo de Gauss-Jordan.

El algoritmo de Gauss-Jordan nos ayudan a resolver sistema no-homogeneos de $m$ ecuaciones con $n$ incognitas, es decir,  
$$
\begin{cases}
    a_{11}x_1 + a_{12}x_2 + \dots + a_{1n}x_n = b_1 \\
    a_{21}x_1 + a_{22}x_2 + \dots + a_{2n}x_n = b_2 \\
    \vdots \\
    a_{m1}x_1 + a_{m2}x_2 + \dots + a_{mn}x_n = b_m.
\end{cases}
$$
El proceso es bastante secillo de aplicar, se lleva al sistema a su *matriz aumentada* y se hacen operaciones "elementales" que llevan a la resolución (o no) de un sistema.
Las preguntas a responder son ¿Por qué funciona? Si es un algoritmo ¿Se puede programar? 

## Teoría 

**Definición.-** Las operaciones elementales para una matriz $A_{m\times n}$ son:  

1. Intercambiar dos renglones (columnas).
2. Multiplicar cualquier renglon (columna) por un escalar distinto de cero.
3. Sumar un multiplo de un renglon (columna) a otro renglon (columna).

Veamos el código para cada una de la operaciones. 

In [1]:
A=[[1,2,3,14],[2,-1,1,5],[3,-1,1,10]]

def change_rows(A,i,j): #Ingresamos la matriz, y los renglones que queremos cambiar. 
   A[i], A[j]=A[j], A[i] #Cambiasmos los renglones AL MISMO TIEMPO. 
   return A
print(change_rows(A,0,1))

def mult_row(A,i,c): #Multiplicar un renglon por un escalar.
   A[i] = [c * elem for elem in A[i]] #Para cada elemento en A[i] lo multiplicamos por c y sustituimos toda la sublista. 
   return A
print(mult_row(A,0,5))

def add_rows(A,i,j,c): #Sumar c veces el renglon i con el renglon j.
   A[j] = [A[j][k] + c * A[i][k] for k in range(len(A[0]))] #Sustituir el renglon j. 
   return A
   
#Notemos que la matriz A se va modificando cada vez que le aplicamos una función. 

[[2, -1, 1, 5], [1, 2, 3, 14], [3, -1, 1, 10]]
[[10, -5, 5, 25], [1, 2, 3, 14], [3, -1, 1, 10]]


 **Definición.-** Una matriz elemental $E_{n\\times n}$ es la matriz identidad $I_n$ después de aplicarle alguna de las tres operaciones elmentales.
 $$ E_1 = \begin{bmatrix} 0 & 1 & 0 \\ 1 & 0 & 0 \\ 0 & 0 & 1 \end{bmatrix}, \quad E_2 = \begin{bmatrix} 1 & 0 & -2 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}. $$

 ¿Cuáles fueron las operaciones aplicadas? Definimos la matriz identidad y le podemos aplicar las operaciones elementales. 

In [2]:
def identity_n(n):
    I=[[0]*n for i in range(n)]
    for i in range(n):
        I[i][i]=1
    return I
print(f'Matriz identiddad de 4x4: {identity_n(4)}.\n')

print(f'Intercambiamos el segundo y primer renglon: {change_rows(identity_n(3),0,1)}.\n') 
I_3=identity_n(3)
print(f'Multiplicamos el tercer renglon por -2 y se los sumamos al primero: {add_rows(I_3,2,0,-2)}.\n')

Matriz identiddad de 4x4: [[1, 0, 0, 0], [0, 1, 0, 0], [0, 0, 1, 0], [0, 0, 0, 1]].

Intercambiamos el segundo y primer renglon: [[0, 1, 0], [1, 0, 0], [0, 0, 1]].

Multiplicamos el tercer renglon por -2 y se los sumamos al primero: [[1, 0, -2], [0, 1, 0], [0, 0, 1]].



**Teorema.-** Sean $A_{m\times n}$ y $B_{m\times n}$ otra matriz que resulta de aplicar alguna operación elemental de renglones (columnas) a $A$. Entonces, existe una matriz elemental $E$ de tamaño $m \times m $ ($n \times n$) tal que $B=EA$ ($B=AE$). De hecho, $E$ se obtiene de $I_m$ ($I_n$) después de aplicarle la mismas operaciones elementales de renglones (columnas) que fueron aplicados a $A$ para obtener $B$.

$$ B_{3 \times 4} = \begin{bmatrix} 2 & -1 & 1 & 5 \\ 1 & 2 & 3 & 14 \\ 3 & -1 & 1 & 10 \end{bmatrix} = \begin{bmatrix} 0 & 1 & 0 \\ 1 & 0 & 0 \\ 0 & 0 & 1 \end{bmatrix} \begin{bmatrix} 1 & 2 & 3 & 14 \\ 2 & -1 & 1 & 5 \\ 3 & -1 & 1 & 10 \end{bmatrix}E_3A_{3\times 4}.$$

In [3]:
# Generar un código que compare cuando dos matrices son iguales, considerando: 
# Tamaño de matriz (puede que ChatGPT no lo considere). 
# Checar que sean iguales entrada a entrada. 

# ¿Qué tienen que ver las operaciones elementales con el algoritmo de G-J?

**Teorema.-** El rango de una matriz es igual al número más grande de sus vectores columna linealmente independientes.

**Proposición.-** Las operaciones elementales de una matriz preservan su rango.

Si pensamos a una matriz de $A_{m \times n}$ como una transformación lineal $A:\mathbb{R}^n \rightarrow \mathbb{R}^m$, el rango es la dimensión de su imagen como subespacio vectorial de contradominio $\mathbb{R}^n$, es decir, $\dim (\text{im}(A))=\text{rank}(A).$

**Teorema.-** Si $A_{m\times n}$ es una matriz de rango $r$, entonces $r \leq m$, $r\leq n$ y existe un número finito de operaciones elementales por renglon y columnas que transforman a $A$ en una matriz del la forma $$ D_{m \times n} = \begin{bmatrix} I_r & O_1  \\ O_2 & O_3\end{bmatrix},$$

es decir, una matriz diagonal, tal que $D_{ii}=1$ si $i\leq r$ y $D_{ij}=0$ para $i\neq j$.

Por ejemplo, la matriz $$A_{4 \times 5} = \begin{bmatrix} 0 & 2 & 4 & 2 & 2\\ 4 & 4 & 4 & 8 & 0 \\ 8 & 2 & 0 & 10 & 2 \\ 6 & 3 & 2 & 9 & 1 \end{bmatrix} \to D_{4 \times 5} = \begin{bmatrix} 1 & 0 & 0 & 0 & 0\\ 0 & 1 & 0 & 0 & 0 \\ 0 & 0 & 1 & 0 & 0 \\ 0 & 0 & 0 & 0 & 0 \end{bmatrix}.$$

Gracias al los teoremas y las propocisión tenemos que $\text{rank}(A)=\text{rank}(D)=3$.

# Regresando a sistemas de ecuaciones.

Un sistema de ecuaciones se puede arreglar de manera matricial como $Ax=b$ de la siguiente manera:

$$ \begin{bmatrix}
    a_{11} & a_{12} & \dots  & a_{1n} \\
    a_{21} & a_{22} & \dots  & a_{2n} \\
    \vdots & \vdots & \ddots & \vdots \\
    a_{m1} & a_{m2} & \dots  & a_{mn}
\end{bmatrix}
\begin{bmatrix}
    x_1 \\
    x_2 \\
    \vdots \\
    x_n
\end{bmatrix}
=
\begin{bmatrix}
    b_1 \\
    b_2 \\
    \vdots \\
    b_m
\end{bmatrix}$$

**Teorema.-** Sea $Ax=b$ un sistema de $n$ ecuaciones lineales con $n$ incognitas. La matriz $A$ es invertible si y solo si el sistema tiene una única solución.

Para aplicar el algoritmo, construimos la matriz aumentada. 
$$
\left[
\begin{array}{cccc|c}
    a_{11} & a_{12} & \dots & a_{1n} & b_1 \\
    a_{21} & a_{22} & \dots & a_{2n} & b_2 \\
    \vdots & \vdots & \ddots & \vdots & \vdots \\
    a_{n1} & a_{n2} & \dots & a_{nn} & b_n
\end{array}
\right]
$$
y le aplicamos operaciones elementales hasta llevarla a una matriz mas sencilla.

La idea es ingresar al sistema el número de incognitas ($n$) los coeficientes de las ecuaciones ($a_{ij}$), que vaya acomodando los coeficientes en la matriz aumentada para después aplicarle el algoritmo a dicha matriz.

Veamos el código para ingresar el número de incognitas.

In [4]:
n=int(input('Ingresar el número de icognitas: '))
print(n)

3


Ahora, construimos la matriz aumentada de un sistema en particular para ejemplificar. 
$$
\begin{cases}
    6x + 2y + 3z = 4 \\
    5x + 6y + 7z = 8 \\
    9x + 0y + 1z = 2.
\end{cases}
$$
Para ello usaremos la matriz de "ceros" para después sustituir paso a paso los coeficientes del sistema.

In [5]:
import numpy as np 
A=np.zeros((n,n+1))  #Construimos la matriz de puros ceros del tamaño correcto para la matriz aumentada.
print(f'Matriz de nx(n+1) \n {A}.\n')
print('Ingresar los coeficientes del sistema:')

for i in range(n):
    for j in range(n+1):
        A[i][j]=float(input('A['+str(i)+']['+str(j)+']='))
print(f'Matriz aumentada del sistema:\n {A}.')


Matriz de nx(n+1) 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]].

Ingresar los coeficientes del sistema:
Matriz aumentada del sistema:
 [[6. 2. 3. 4.]
 [5. 6. 7. 8.]
 [9. 0. 1. 2.]].


# ¿Cómo reorganizamos el sistema? 

El algoritmo de G-J nos pide un pivote para ir eliminando los elementos de una columna, por ejemplo, si dejamos la matriz como está y escojemos $a_{11}=6$ como el pivote, para "eliminar" al elemento $a_{21}=5$, haríamos la operaciones $(-5/6)R_1+R_2$, con lo cual obtenemos: 

$$ \left[ \begin{array}{ccc|c} 6 & 2 & 3 & 4 \\ 5 & 6 & 7 & 8 \\ 9 & 0 & 1 & 2 \end{array} \right] \rightarrow \left[ \begin{array}{ccc|c} 6 & 2 & 3 & 4 \\ 0 & 13/3 & 9/2 & 14/3 \\ 9 & 0 & 1 & 2 \end{array} \right].$$
Uno de los "problemas" que pueden surgir es la aparición de fracciones, que son números que ocupan espacio en la memoria. Para evitar dicho problema, atacamos el algoritmo desde otro ángulo usando multiplicación, la cual ocupa menos espacio y es un procesamiento mas sencillo. La idea es reorganizar la matriz, de tal manera que el número mas grande en valor absoluto sea nuestro pivote y con ese realizar las operaciones de "eliminación" usando al la entrada justo debajo del pivote como factor. Por ejemplo, multiplicamos el segundo renglon por el pivote $=9$ para después sumarle al segundo renglo el primer renglon ,ultiplicado por $-6=$ factor, es decir: 
$$ \left[ \begin{array}{ccc|c}6 & 2 & 3 & 4 \\ 5 & 6 & 7 & 8 \\ 9 & 0 & 1 & 2 \end{array} \right] \rightarrow \left[ \begin{array}{ccc|c} 9 & 0 & 1 & 2 \\ 6 & 2 & 3 & 4 \\ 5 & 6 & 7 & 8 \end{array} \right] \rightarrow \left[ \begin{array}{ccc|c} 9 & 0 & 1 & 2 \\ 54 & 18 & 27 & 36 \\ 5 & 6 & 7 & 8 \end{array} \right]\rightarrow \left[ \begin{array}{ccc|c} 9 & 0 & 1 & 2 \\ 0 & 18 & 21 & 18 \\ 5 & 6 & 7 & 8 \end{array} \right] .$$

La meta es llevar la matriz a una matriz triángular superior, que es una matriz de ceros por debajo de la diagonal. 

In [6]:
def reorganizar_sistema(A): 
    A=A.tolist()
    A.sort(key=lambda x: [abs(i) for i in x], reverse=True) #Complejidad n*log_2(n)
    A=np.array(A)
    return A
A=reorganizar_sistema(A)
print(A) 


[[9. 0. 1. 2.]
 [6. 2. 3. 4.]
 [5. 6. 7. 8.]]


In [7]:
for k in range(n): #range(3)=[0,1,2] k=0
    pivote=A[k][k] #A[0][0]=9
    if pivote ==0: #Si el pivote es cero, continua al siguiente valor de k.
        continue
    for i in range(k+1,n): #range(1,3)=[1,2] i=1
        factor=A[i][k] #A[1][0]=5
        if factor ==0: #Si el factor es cero, continua al siguiente valor de i.
            continue
        for j in range(k,n+1): #range(0,4)=[0,1,2,3] j=0, j=1
            A[i][j]=A[k][j]*(factor)+(A[i][j]*(-pivote)) #A[1][0]=A[0][0]*5+(A[1][0](-9))=9*6+(6)(-9)=54-54=0
print(A)
#El orden de la operación se calcula por cada iteración, i.e, cada for: O(n*n*n)=O(3^3)=O(3^3)=O(27) mínimo de operaciones si la matriz fuera de 3x3. 


[[  9.   0.   1.   2.]
 [  0. -18. -21. -24.]
 [  0.   0.  90. 180.]]


Podría suceder que después de llevar la matriz a una matriz triángular superior, alguno de los renglones o columnas sea de solo ceros. Según la teoría el sistema no tiene solución única, o no tiene solución. 

In [8]:
import sys 
for i in range(n):
    if np.all(A[i,:-1]==0) and A[i,-1] !=0:
        print('El sistema no tiene solución única o no tiene solución.')
        sys.exit()


Para terminar el algoritmo de G-J, generamos el vector "solución" donde ya no nos podemos escapar de dividir. Pero en el proceso nos hemos ahorrado usar decimales indiscriminadamente. Como la matriz que generamos es triángular superior de tamaño $n \times (n+1)$, si el sistema tiene solución, los valores $a_{n\times n}$ y $b_n$ dan la solución de último valor del sistema $x_n=b_n/a_{nn}$.  

In [9]:
S=np.zeros(n)

for i in range(n-1,-1,-1): #n=3 range(2,-1,-1)=[2,1,0]
    suma=0
    for j in range(i+1,n): #range(2,3)=[3]
        suma += A[i][j]*S[j] #suma=0+A[2][3]*S[3]
    S[i]=(A[i][n]-suma)/A[i][i] #S[2]=(A[2][3]-suma)/A[2][2]

print('Soluciones:')
for i in range(n):
    print(f'x{i+1}={S[i]}')

Soluciones:
x1=0.0
x2=-1.0
x3=2.0
