# El algoritmo de Gauss-Jordan.

El algoritmo de Gauss-Jordan nos ayudan a resolver sistema no-homogeneos de $m$ ecuaciones con $n$ incognitas, es decir,  
$$
\begin{cases}
    a_{11}x_1 + a_{12}x_2 + \dots + a_{1n}x_n = b_1 \\
    a_{21}x_1 + a_{22}x_2 + \dots + a_{2n}x_n = b_2 \\
    \vdots \\
    a_{m1}x_1 + a_{m2}x_2 + \dots + a_{mn}x_n = b_m.
\end{cases}
$$
El proceso es bastante secillo de aplicar, se lleva al sistema a su *matriz aumentada* y se hacen operaciones "elementales" que llevan a la resolución (o no) de un sistema.
Las preguntas a responder son ¿Por qué funciona? Si es un algoritmo ¿Se puede programar? 

## Teoría 

**Definición.-** Las operaciones elementales para una matriz $A_{m\times n}$ son:  

1. Intercambiar dos renglones (columnas).
2. Multiplicar cualquier renglon (columna) por un escalar distinto de cero.
3. Sumar un multiplo de un rengon (columna) a otro renglon (columna).

Veamos el código para cada una de la operaciones. 

In [1]:
A=[[1,2,3,14],[2,-1,1,5],[3,-1,1,10]]

def change_rows(A,i,j): #Ingresamos la matriz, y los renglones que queremos cambiar. 
   A[i], A[j]=A[j], A[i] #Cambiasmos los renglones AL MISMO TIEMPO. 
   return A
print(change_rows(A,0,1))

def mult_row(A,i,c): #Multiplicar un renglon por un escalar.
   A[i] = [c * elem for elem in A[i]] #Para cada elemento en A[i] lo multiplicamos por c y sustituimos toda la sublista. 
   return A
print(mult_row(A,0,5))

def add_rows(A,i,j,c): #Sumar c veces el renglon i con el renglon j.
   A[j] = [A[j][k] + c * A[i][k] for k in range(len(A[0]))] #Sustituir el renglon j. 
   return A
   
#Notemos que la matriz A se va modificando cada vez que le aplicamos una función. 

[[2, -1, 1, 5], [1, 2, 3, 14], [3, -1, 1, 10]]
[[10, -5, 5, 25], [1, 2, 3, 14], [3, -1, 1, 10]]


**Definición.-** Una matriz elmental $E_{n\times n}$ es la matriz identidad $I_n$ después de aplicarle alguna de las tres operaciones elmentales. 
$$ E_1 = \begin{bmatrix} 0 & 1 & 0 \\ 1 & 0 & 0 \\ 0 & 0 & 1 \end{bmatrix}, \quad E_2 = \begin{bmatrix} 1 & 0 & -2 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{bmatrix}. $$



In [2]:
def indentity_n(n):
    I=[[0]*n for i in range(n)] 
    for i in range(n): #range(n)=[0,1,2,...,n-1] i toma los valores 0,1,2,..., n-1
        I[i][i]=1
    return I
#¿Qué operaciones aplicamos? 

**Teorema.-** Sean $A_{m\times n}$ y $B_{m\times n}$ otra matriz que resulta de aplicar alguna operación elemental de renglones (columnas) a $A$. Entonces, existe una matriz elemental $E$ de tamaño $m \times m $ ($n \times n$) tal que $B=EA$ ($B=AE$). De hecho, $E$ se obtiene de $I_m$ ($I_n$) después de aplicarle la mismas operaciones elementales de renglones (columnas) que fueron aplicados a $A$ para obtener $B$. 
$$ B_{3 \times 4} = \begin{bmatrix} 2 & -1 & 1 & 5 \\ 1 & 2 & 3 & 14 \\ 3 & -1 & 1 & 10 \end{bmatrix} = \begin{bmatrix} 0 & 1 & 0 \\ 1 & 0 & 0 \\ 0 & 0 & 1 \end{bmatrix} \begin{bmatrix} 1 & 2 & 3 & 14 \\ 2 & -1 & 1 & 5 \\ 3 & -1 & 1 & 10 \end{bmatrix}E_3A_{3\times 4}.$$



In [3]:
#Generemos una función que nos diga cuando dos matrices son iguales. 

# ¿Qué tienen que ver las operaciones elementales con el algoritmo de G-J?

**Teorema.-** El rango de una matriz es igual al número más grande de sus vectores columna linealmente independientes. 

**Proposición.-** Las operaciones elementales de una matriz preservan su rango. 

Si pensamos a una matriz de $A_{m \times n}$ como una transformación lineal $A:\mathbb{R}^m\rightarrow \mathbb{R}^n$, el rango es la dimensión de su imagen como subespacio vectorial de contradominio $\mathbb{R}^n$, es decir, $\dim (\text{im}(A))=\text{rank}(A).$ 

**Teorema.-** Si $A_{m\times n}$ es una matriz de rango $r$, entonces $r \leq m$, $r\leq n$ y existe un número finito de operaciones elementales por renglon y columnas que transforman a $A$ en una matriz del la forma $$ D_{m \times n} = \begin{bmatrix} I_r & O_1  \\ O_2 & O_3\end{bmatrix},$$
es decir, una matriz diagonal, tal que $D_{ii}=1 si $i\leq r$ y $D_{ij}=0$ para $i\neq j$.

Por ejemplo, la matriz $$A_{4 \times 5} = \begin{bmatrix} 0 & 2 & 4 & 2 & 2\\ 4 & 4 & 4 & 8 & 0 \\ 8 & 2 & 0 & 10 & 2 \\ 6 & 3 & 2 & 9 & 1 \end{bmatrix} \to D_{4 \times 5} = \begin{bmatrix} 1 & 0 & 0 & 0 & 0\\ 0 & 1 & 0 & 0 & 0 \\ 0 & 0 & 1 & 0 & 0 \\ 0 & 0 & 0 & 0 & 0 \end{bmatrix}.$$

Gracias al los teoremas y las propocisión tenemos que $\text{rank}(A)=\text{rank}(D)=3$.

# Regresando a sistemas de ecuaciones.

Un sistema de ecuaciones se puede arreglar de manera matricial como $Ax=b$ de la siguiente manera:  
$$\begin{bmatrix}
    a_{11} & a_{12} & \dots  & a_{1n} \\
    a_{21} & a_{22} & \dots  & a_{2n} \\
    \vdots & \vdots & \ddots & \vdots \\
    a_{m1} & a_{m2} & \dots  & a_{mn}
\end{bmatrix}
\begin{bmatrix}
    x_1 \\
    x_2 \\
    \vdots \\
    x_n
\end{bmatrix}
=
\begin{bmatrix}
    b_1 \\
    b_2 \\
    \vdots \\
    b_m
\end{bmatrix}. $$

**Teorema.-** Sea $Ax=b$ un sistema de $n$ ecuaciones lineales con $n$ incognitas. La matriz $A$ es invertible si y solo si el sistema tiene una única solución.

Para aplicar el algoritmo de Gauss-Jordan tomamos la matriz aumentada 
$$ \left[
\begin{array}{cccc|c}
    a_{11} & a_{12} & \dots  & a_{1n} & b_1 \\
    a_{21} & a_{22} & \dots  & a_{2n} & b_2 \\
    \vdots & \vdots & \ddots & \vdots & \vdots \\
    a_{n1} & a_{n2} & \dots  & a_{nn} & b_n
\end{array}
\right] $$
y le aplicamos operaciones elementales hasta llevarla a una matriz mas sencilla.

La idea es ingresar al sistema el número de incognitas ($n$) los coeficientes de las ecuaciones ($a_{ij}$), que vaya acomodando los coeficientes en la matriz aumentada para después aplicarle el algoritmo a dicha matriz.

Veamos el código para ingresar el número de incognitas.

In [4]:
n=int(input('Ingresar el número de incognitas:'))

Ahora, construimos la matriz aumentada, para ello usaremos la matriz de "ceros" para después sustituir paso a paso los coeficientes del sistema. 

In [ ]:
import numpy as np

A = np.zeros((n,n+1)) #Construimos la matriz de puros ceros del tamaña que debería tener la matriz aumentada. 

print(f'{A}\n')

print('Ingresar los coefecientes del sistema:')

for i in range(n): #range(n)=[0,1,2,...,n-1]
    for j in range(n+1): #range(n+1)=[0,1,2,...,n]
        A[i][j] = float(input( 'A['+str(i)+']['+str(j)+']=')) 
print(A)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Ingresar los coefecientes del sistema:
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]
 [9. 0. 1. 2.]]


Modificar 

In [6]:
def reorganizar_sistema(A):
    A=A.tolist()
    A.sort(key=lambda x: [abs(i) for i in x], reverse=True) #Acomodo en orden lexicográfico con respecto al valor absoluto. 
    A=np.array(A)# Intercambiar filas correctamente
    return A
A=reorganizar_sistema(A)
print(A)

[[9. 0. 1. 2.]
 [5. 6. 7. 8.]
 [1. 2. 3. 4.]]


In [7]:
#Discutir a que queremos llevar la matriz.

In [8]:
for k in range(n):
  pivote=A[k][k]
  if pivote ==0:
    continue
  for i in range(k+1,n):
    factor=A[i][k]
    if factor == 0:
      continue
    for j in range(k,n+1):
        A[i][j]=A[k][j]*(factor)+(A[i][j]*(-pivote))
print(A)

[[   9.    0.    1.    2.]
 [   0.  -54.  -58.  -62.]
 [   0.    0. -360. -720.]]


In [9]:
#Discutir como y cuando se puede obtener el resultado.

In [10]:
import sys 
for i in range(n):
    if np.all(A[i, :-1] == 0) and A[i, -1] != 0:
        print("El sistema no tiene solución.")
        sys.exit()

In [11]:
S = np.zeros(n) 

for i in range(n-1, -1, -1): #range(n-1,-1,-1)=[4,3,2,1,0] si n=5
    suma = 0 #Guardamos una suma.
    for j in range(i+1, n): 
        suma += A[i][j] * S[j]  # Sumar los términos ya conocidos
    S[i] = (A[i][n] - suma) / A[i][i]

print("Soluciones:")
for i in range(n):
    print(f'x{i+1} = {S[i]}')

Soluciones:
x1 = 0.0
x2 = -1.0
x3 = 2.0
